# Generated by Django 4.1.3 on 2022-11-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.FileField(blank=True, upload_to='users/teste/'),
        ),
    ]
