# Generated by Django 4.1.3 on 2022-11-11 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data_upload',
            field=models.DateTimeField(verbose_name=datetime.date(2022, 11, 11)),
        ),
    ]
